### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'GvLib.Managed.dll'

### ISSUE THREAD

**Issue by DeV1L** [Microsoft/GVFS#52]
OS: Windows 10 1703 (build 15063.726)
GVFS: 1.0.17318.1
Git: 2.15.0.gvfs.1.preview.4

I've just installed GVFS and the latest Git  and tried to clone repository from VSTS.

```
C:\TEST\GVFS>gvfs clone https://arkadiumarena.visualstudio.com/Phoenix%20Games/_git/five-roll-pixi
Clone parameters:
  Repo URL:     https://arkadiumarena.visualstudio.com/Phoenix%20Games/_git/five-roll-pixi
  Cache Server: Default
  Destination:  C:\TEST\GVFS\five-roll-pixi
Authenticating...Succeeded
Querying remote for config...Succeeded
Using cache server: None (https://arkadiumarena.visualstudio.com/Phoenix%20Games/_git/five-roll-pixi)
Cloning...Failed. Run 'gvfs log C:\TEST\GVFS\five-roll-pixi' for more info.
Cannot clone @ C:\TEST\GVFS\five-roll-pixi: System.IO.FileNotFoundException: Could not load file or assembly 'GvLib.Managed.dll' or one of its dependencies. The specified module could not be found.
File name: 'GvLib.Managed.dll'
   at GVFS.GVFlt.GVFltCallbacks.TryPrepareFolderForGVFltCallbacks(String folderPath, String& error)
   at GVFS.CommandLine.CloneVerb.CreateClone(ITracer tracer, GVFSEnlistment enlistment, GitObjectsHttpRequestor objectRequestor, GitRefs refs, String branch) in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\CloneVerb.cs:line 354
   at GVFS.CommandLine.CloneVerb.TryClone(JsonEtwTracer tracer, GVFSEnlistment enlistment, CacheServerInfo cacheServer, RetryConfig retryConfig) in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\CloneVerb.cs:line 297
   at GVFS.CommandLine.CloneVerb.<>c__DisplayClass31_2.<Execute>b__1() in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\CloneVerb.cs:line 143
   at GVFS.Common.ConsoleHelper.<>c__DisplayClass3_0.<ShowStatusWhileRunning>b__0() in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS.Common\ConsoleHelper.cs:line 44
   at GVFS.Common.ConsoleHelper.ShowStatusWhileRunning(Func`1 action, String message, TextWriter output, Boolean showSpinner, String gvfsLogEnlistmentRoot, Int32 initialDelayMs) in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS.Common\ConsoleHelper.cs:line 113
   at GVFS.CommandLine.GVFSVerb.ShowStatusWhileRunning(Func`1 action, String message, Boolean suppressGvfsLogMessage) in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\GVFSVerb.cs:line 148
   at GVFS.CommandLine.CloneVerb.Execute() in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\CloneVerb.cs:line 140
```

**Comment by DeV1L** [comment]
There is C:\ProgramData\GVFS\GVFS.Service\Logs\gvfs_service_20171127_135432.log

```
[11/27/2017 1:54:40 PM] RepoRegistry_Created {"Area":"RepoRegistry","registryParentFolderPath":"C:\\ProgramData\\GVFS\\GVFS.Service","Message":"RepoRegistry created"}
[11/27/2017 1:54:40 PM] Information {"Message":"Starting pipe server with name: GVFS.Service.Pipe"}
[11/27/2017 2:05:14 PM] Information {"Message":"SessionLogon detected, sessionId: 2"}
[11/27/2017 2:05:14 PM] LogonAutomount (Start)
[11/27/2017 2:05:16 PM] AutoMount (Start)
[11/27/2017 2:05:21 PM] AutoMount (Stop) {"DurationMs":2297}
[11/27/2017 2:05:21 PM] LogonAutomount (Stop) {"DurationMs":7140}
```

**Comment by jamill** [comment]
Hi @DeV1L - we are unable to reproduce this error. Do you have Visual Studio installed on this machine? Would you be able to collect assembly binding logs for this issue (using [fuslogvw](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer))?

Can you verify that GvLib.Managed.dll is in your "c:\Program Files\GVFS directory"? Could this machine have any restrictions that might cause this (e.g. restrictions on running native / non-strong named signed code)?

**Comment by SergioLuis** [comment]
I'm experimenting the same issue on a clean machine (Windows 10 Fall Creators Update running as a VirtualBox virtual machine). I have not installed Visual Studio on it, so I don't have fuslogvw to check the logs.

The assembly `GvLib.Managed.dll` is indeed inside `C:\Program Files\GVFS`.

I installed the 1.0.0 release of GVFS available on this repository.

**Comment by jamill** [comment]
I was able to reproduce this. The machine I originally used did not have Visual Studio on it, but it wasn't clean enough.

I think you are missing the MSVC++ redistributable. Could you install it from one of the following links and let us know if this resolves your problem? We will look at fixing this issue as well so this step is not needed.

[Visual C++ downloads](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
[VS 2017 VC++ redistributable](https://go.microsoft.com/fwlink/?LinkId=746572)

**Comment by SergioLuis** [comment]
@jamill I can confirm that installing the MSVC++ redistributable fixes the issue.

I tested this again on a new, clean Windows 10 FCU machine.

Thank you!

**Comment by DeV1L** [comment]
VS 2017 VC++ redistributable
