### ISSUE TITLE
Error when cloning an empty repo

### ISSUE THREAD

**Issue by stefanes** [Microsoft/GVFS#58]
Calling `$ gvfs clone https://<user>.visualstudio.com/_git/<proj>` on an empty repo gives the following error:
```
Clone parameters:
  Repo URL:     https://<user>.visualstudio.com/_git/<proj>
  Cache Server: Default
  Destination:  <path>
Authenticating...Succeeded
Querying remote for config...Succeeded
Using cache server: None (https://<user>.visualstudio.com/_git/<proj>)
Cloning...Failed. Run 'gvfs log <path>' for more info.
Cannot clone @ <path>: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at GVFS.CommandLine.CloneVerb.CreateClone(ITracer tracer, GVFSEnlistment enlistment, GitObjectsHttpRequestor objectRequestor, GitRefs refs, String branch) in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\CloneVerb.cs:line 368
   at GVFS.CommandLine.CloneVerb.TryClone(JsonEtwTracer tracer, GVFSEnlistment enlistment, CacheServerInfo cacheServer, RetryConfig retryConfig) in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\CloneVerb.cs:line 297
   at GVFS.CommandLine.CloneVerb.<>c__DisplayClass31_2.<Execute>b__1() in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\CloneVerb.cs:line 143
   at GVFS.Common.ConsoleHelper.<>c__DisplayClass3_0.<ShowStatusWhileRunning>b__0() in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS.Common\ConsoleHelper.cs:line 44
   at GVFS.Common.ConsoleHelper.ShowStatusWhileRunning(Func`1 action, String message, TextWriter output, Boolean showSpinner, String gvfsLogEnlistmentRoot, Int32 initialDelayMs) in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS.Common\ConsoleHelper.cs:line 113
   at GVFS.CommandLine.GVFSVerb.ShowStatusWhileRunning(Func`1 action, String message, Boolean suppressGvfsLogMessage) in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\GVFSVerb.cs:line 148
   at GVFS.CommandLine.CloneVerb.Execute() in C:\Repos\GitHubUpdate\Internal\GVFS\GVFS\CommandLine\CloneVerb.cs:line 140
```

**Comment by sanoursa** [comment]
Have you cleansed your outputs, or are those the actual strings? Just trying to figure out which string it's choking on :-)

If you're cloning an actually totally empty repo, then some sort of error is to be expected (and not something we've really optimized a nice behavior for), because right now it assumes that your repo must have at least a root .gitattributes file in it. GVFS relies heavily on git's sparse-checkout feature, and sparse-checkout can't be used without at least one file included, so this is a limitation we inherited.

**Comment by stefanes** [comment]
Ok, understood. Do what you will this issue, just something I picked up when trying things out.

Yes, I have replaced the stuff in `<...>`. `<path>` above is the local path to the gvfs repo, e.g. `C:\gvfs-repos\<proj>`.

`<user>` is of course the VSTS user name and `<proj>` the project in VSTS.

**Comment by tomspilman** [comment]
I ran into this as well setting up a new repo from VSTS.

**Comment by raspy** [comment]
This also fails the same way when the repository exists, but the user is not authorized to read it. I ran into this problem with Bitbucket Server and their [GVFS plugin](https://marketplace.atlassian.com/apps/1217957/gvfs-for-bitbucket-server?hosting=server&tab=overview).

**Comment by kmkive** [comment]
You cannot clone an empty repo, you will get this error: This branch does not contain a .gitattributes file in the root folder.  This file is required by GVFS clone

Adding .gitattributes and .gitignore to repo resolved my issue with exactly same problems

**Comment by clearwaterstream** [comment]
I too run into the same issue. Created an emptry repo in Azure DevOps, installed v1.0.19130.1 and got the KeyNotFound exception ...

**Comment by clearwaterstream** [comment]
P.S. If you place a .gitattributes file with `* -text` as per instructions then all is good.
