### ISSUE TITLE
 Collection was modified crash

### ISSUE THREAD

**Issue by tomspilman** [Microsoft/GVFS#64]
I was running this command line on a subfolder of my repo:
```
 gvfs prefetch --files *.png --hydrate
```
... and i got this crash:

```
Fetching blobs and hydrating files from https://XXXXX.visualstudio.com/XXXXX/_git/XXXXX...\
Unhandled Exception:

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at FastFetch.Jobs.ReadFilesJob.DoWork() in C:\Repos\GitHubUpdate\Internal\GVFS\FastFetch\Jobs\ReadFilesJob.cs:line 45
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by sanoursa** [comment]
Thanks for the bug report, and for all of your feedback!

This bug was fixed in [GVFS 1.0.18026.1](https://github.com/Microsoft/GVFS/releases/tag/v1.0.18026.1)
