### ISSUE TITLE
Could not find any recognizable digits

### ISSUE THREAD

**Issue by mazong1123** [Microsoft/GVFS#67]
Recently we have this issue while using gvfs clone. The stacktrace is:

```
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToByte(String value, Int32 fromBase)
   at GVFS.Common.Git.GitPathConverter.ConvertPathOctetsToUtf8(String filePath) in E:\A\_work\45\s\GVFS\GVFS.Common\Git\GitPathConverter.cs:line 34
   at GVFS.Common.Git.DiffTreeResult.ConvertPathToAbsoluteUtf8Path(String repoRoot, String relativePath) in E:\A\_work\45\s\GVFS\GVFS.Common\Git\DiffTreeResult.cs:line 110
   at GVFS.Common.Git.DiffTreeResult.ParseFromLsTreeLine(String line, String repoRoot) in E:\A\_work\45\s\GVFS\GVFS.Common\Git\DiffTreeResult.cs:line 72
   at GVFS.CommandLine.GVFSVerb.<>c__DisplayClass44_0.<TryDownloadRootGitAttributes>b__0(String line) in E:\A\_work\45\s\GVFS\GVFS\CommandLine\GVFSVerb.cs:line 396
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Looking at the code:

https://github.com/Microsoft/GVFS/blob/522d018a2e34a13e56a94b158b7bc58ba3009a1d/GVFS/GVFS.Common/Git/DiffTreeResult.cs#L108-L111

and this code:

https://github.com/Microsoft/GVFS/blob/3c09517e5dd154a63592ac2d78c582b9629dad90/GVFS/GVFS.Common/Git/GitPathConverter.cs#L34

Seems like if there's any "\\" in the path we would have this issue. Any reason?

**Comment by derrickstolee** [comment]
@mazong1123 could you provide the working directory where you are running `gvfs clone` and the full command? What part of the command has a '\'?

**Comment by sanoursa** [comment]
This issue is now understood and we have a fix for it in progress, to fail with a better error message. The root cause was that they had accidentally created a path that was not a legal Windows path, so they have worked around it by fixing their git tree. We will look at actually supporting such paths as we work on the Mac implementation.
